swagger: "2.0"
info:
  description: "A framework for creating a webportal with simple turn-based games"
  title: "TGFW"
  version: 1.0.0


tags:
- name: "Chess"
  description: "Chess game created on our framework"
paths:
  /chess/get/{id}:
    get:
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Numeric ID of the chess instance to get
      tags:
      - "Chess"
      description: "Returns one created chess instance by id"
      operationId: "getChess"
      responses:
        "200":
          description: "Successful operation"
          schema: 
            $ref: "#/definitions/Chess"
   
  /chess/create:
    get:
      tags:
      - "Chess"
      description: "Create chess instance and returns its id"
      operationId: "createChess"
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "integer"
 
definitions:
  Chess:
    type: "object"
    properties:
      Board:
        type: "string"
        format: "int64"
      Tiles:
        $ref: "#/definitions/Tile"
  Tile:
    type: "object"
    properties:
      texturePath: 
        type: "string"
      pieces: 
        type: "string"
