name: LandsAsp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build for Linux
      run: dotnet build --runtime linux-x64 -property:SelfContained=true Back/LandsAsp
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: LandsAsp_linux
        path: Back/LandsAsp/bin/Debug/net5.0/linux-x64
    - name: Build for Windows
      run: dotnet build --runtime win10-x64 -property:SelfContained=true Back/LandsAsp
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: LandsAsp_win
        path: Back/LandsAsp/bin/Debug/net5.0/win10-x64
